name: quickcar_aplication
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  get_it: ^8.0.0
  dartz:
  collection: ^1.18.0               
  http_parser: ^4.0.2               
  leak_tracker: ^10.0.5             
  leak_tracker_flutter_testing: ^3.0.5 
  material_color_utilities: ^0.11.1 
  meta: ^1.15.0                     
  string_scanner: ^1.2.0        
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  confetti: ^0.8.0
  skeletonizer: ^1.4.2
  auto_size_text: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  # Fonts section
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
    - family: Eina02
      fonts:
        - asset: assets/fonts/Eina02-BoldItalic.ttf
          weight: 700
          style: italic
