// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJDbqc7wKVcj1v8lHV4mjswywUMkaGaE',
    appId: '1:71992714639:web:d4466333ce3bea03bc17fa',
    messagingSenderId: '71992714639',
    projectId: 'quickarapp',
    authDomain: 'quickarapp.firebaseapp.com',
    storageBucket: 'quickarapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqU2BbpvW32GaWvr2co4-CBHvPFOSzgVk',
    appId: '1:71992714639:android:0b8db74f528b3defbc17fa',
    messagingSenderId: '71992714639',
    projectId: 'quickarapp',
    storageBucket: 'quickarapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYi7FcswhQFdSXnJmXcHMQht4wnufp--g',
    appId: '1:71992714639:ios:383e81e6b8b48ec5bc17fa',
    messagingSenderId: '71992714639',
    projectId: 'quickarapp',
    storageBucket: 'quickarapp.appspot.com',
    iosBundleId: 'com.example.quickcarAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYi7FcswhQFdSXnJmXcHMQht4wnufp--g',
    appId: '1:71992714639:ios:383e81e6b8b48ec5bc17fa',
    messagingSenderId: '71992714639',
    projectId: 'quickarapp',
    storageBucket: 'quickarapp.appspot.com',
    iosBundleId: 'com.example.quickcarAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZJDbqc7wKVcj1v8lHV4mjswywUMkaGaE',
    appId: '1:71992714639:web:7e1b1660a9bc0cc0bc17fa',
    messagingSenderId: '71992714639',
    projectId: 'quickarapp',
    authDomain: 'quickarapp.firebaseapp.com',
    storageBucket: 'quickarapp.appspot.com',
  );
}
